import type { Metadata } from 'next'
import { Kaisei_Decol, Poppins } from 'next/font/google'
import './globals.css'

const kaisei = Kaisei_Decol({
	variable: '--font-kaisei',
	subsets: ['latin'],
	weight: ['700'],
	display: 'swap',
})

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${kaisei.variable} ${poppins.variable} antialiased`}>{children}</body>
		</html>
	)
}
